Vagrant.configure("2") do |config|
  config.vm.define "control" do |control|
    control.vm.box = "ubuntu/focal64"
    control.vm.network "private_network", ip: "192.168.56.5" 
    control.vm.provision "shell",
      inline: "/home/nick/repos/Caltech-config-management/controlsetup.sh"

  end

  config.vm.define "web" do |web|
    web.vm.box = "ubuntu/focal64"
    web.vm.network "private_network", ip: "192.168.56.6"
  end

  config.vm.define "db" do |db|
    db.vm.box = "ubuntu/focal64"
    db.vm.network "private_network", ip: "192.168.56.7"
  end
end