Vagrant.configure("2") do |config|
  config.vm.define "control" do |subconfig|
    subconfig.vm.box = "ubuntu/trusty64"
  end

  config.vm.define "web" do |subconfig|
    subconfig.vm.box = "ubuntu/trusty64"
  end

  config.vm.define "db" do |subconfig|
    subconfig.vm.box = "ubuntu/trusty64"
  end
end